name: setup-test-lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - run: make setup
      - run: make start
      - run: make lint
      - name: run tests
        run: make test
